export const hospitals = [
  {
    id: 1,
    slug: 'apollo-delhi',
    name: 'Apollo Hospital Delhi',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1576091160550-112173e7f9db?w=800&h=400&fit=crop',
    rating: 4.8,
    reviews: 324,
    description: 'Leading multi-specialty hospital with state-of-the-art facilities and world-class doctors.',
    beds: 500,
    established: 2000,
    specializations: ['Cardiology', 'Oncology', 'Orthopedics', 'Neurology'],
    accreditations: ['JCI', 'NABH'],
    avgCost: { min: 8000, max: 50000 },
  },
  {
    id: 2,
    slug: 'max-bangalore',
    name: 'Max Healthcare Bangalore',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1581091918492-8ff080ef951e?w=800&h=400&fit=crop',
    rating: 4.7,
    reviews: 287,
    description: 'Advanced medical center specializing in cardiac and orthopedic surgeries.',
    beds: 400,
    established: 2005,
    specializations: ['Cardiology', 'Orthopedics', 'Neurosurgery', 'Gastroenterology'],
    accreditations: ['JCI', 'ISO'],
    avgCost: { min: 10000, max: 45000 },
  },
  {
    id: 3,
    slug: 'fortis-hyderabad',
    name: 'Fortis Hospital Hyderabad',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1519494026067-461c37dd7ce5?w=800&h=400&fit=crop',
    rating: 4.6,
    reviews: 256,
    description: 'Comprehensive healthcare provider with expertise in complex surgeries.',
    beds: 350,
    established: 2008,
    specializations: ['Orthopedics', 'Oncology', 'Neurosurgery', 'Urology'],
    accreditations: ['JCI', 'NABH'],
    avgCost: { min: 9000, max: 48000 },
  },
  {
    id: 4,
    slug: 'american-hospital-dubai',
    name: 'American Hospital Dubai',
    country: 'UAE',
    image: 'https://images.unsplash.com/photo-1516534775068-bb6aaf00db58?w=800&h=400&fit=crop',
    rating: 4.9,
    reviews: 412,
    description: 'Luxury healthcare facility offering premium medical services.',
    beds: 300,
    established: 2002,
    specializations: ['Cardiology', 'Orthopedics', 'IVF', 'Dermatology'],
    accreditations: ['JCI', 'ISO', 'CBAHI'],
    avgCost: { min: 15000, max: 80000 },
  },
  {
    id: 5,
    slug: 'aga-khan-karachi',
    name: 'Aga Khan University Hospital Karachi',
    country: 'Pakistan',
    image: 'https://images.unsplash.com/photo-1631217314831-c6227db76b6e?w=800&h=400&fit=crop',
    rating: 4.7,
    reviews: 198,
    description: 'Premier teaching hospital with cutting-edge medical technology.',
    beds: 450,
    established: 1985,
    specializations: ['Cardiac Surgery', 'Orthopedics', 'Oncology', 'Nephrology'],
    accreditations: ['JCI'],
    avgCost: { min: 7000, max: 40000 },
  },
];

export const doctors = [
  {
    id: 1,
    slug: 'dr-rajesh-sharma',
    name: 'Dr. Rajesh Sharma',
    specialization: 'Cardiac Surgery',
    hospital: 'Apollo Hospital Delhi',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1612349317150-e0a1a03b0c70?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 156,
    experience: 20,
    qualification: 'MD, MCh',
    languages: ['English', 'Hindi'],
    consultationFee: 150,
    description: 'Renowned cardiac surgeon with expertise in complex heart surgeries.',
  },
  {
    id: 2,
    slug: 'dr-priya-gupta',
    name: 'Dr. Priya Gupta',
    specialization: 'Orthopedic Surgery',
    hospital: 'Max Healthcare Bangalore',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1638599810033-ba39fd5faf60?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 143,
    experience: 18,
    qualification: 'MS, DNB',
    languages: ['English', 'Hindi', 'Kannada'],
    consultationFee: 120,
    description: 'Expert in joint replacement and arthroscopic surgeries.',
  },
  {
    id: 3,
    slug: 'dr-ahmed-hassan',
    name: 'Dr. Ahmed Hassan',
    specialization: 'Neurosurgery',
    hospital: 'American Hospital Dubai',
    country: 'UAE',
    image: 'https://images.unsplash.com/photo-1611613535308-eb5fbd8b86b3?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 187,
    experience: 22,
    qualification: 'MD, Fellowship',
    languages: ['English', 'Arabic'],
    consultationFee: 250,
    description: 'Leading neurosurgeon specializing in complex brain and spine surgeries.',
  },
  {
    id: 4,
    slug: 'dr-aisha-khan',
    name: 'Dr. Aisha Khan',
    specialization: 'Oncology',
    hospital: 'Fortis Hospital Hyderabad',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1622803268553-b1b0f85f7e9f?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 127,
    experience: 16,
    qualification: 'MD, DNB',
    languages: ['English', 'Hindi', 'Urdu'],
    consultationFee: 180,
    description: 'Compassionate oncologist with success in cancer treatment protocols.',
  },
  {
    id: 5,
    slug: 'dr-ali-raza',
    name: 'Dr. Ali Raza',
    specialization: 'Orthopedic Surgery',
    hospital: 'Aga Khan University Hospital Karachi',
    country: 'Pakistan',
    image: 'https://images.unsplash.com/photo-1627225924839-c0a59ecd272d?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 134,
    experience: 19,
    qualification: 'MS, FRCS',
    languages: ['English', 'Urdu'],
    consultationFee: 100,
    description: 'Specialist in sports medicine and orthopedic trauma.',
  },
];

export const treatments = [
  {
    id: 1,
    slug: 'heart-bypass-surgery',
    name: 'Heart Bypass Surgery',
    category: 'Cardiology',
    image: 'https://images.unsplash.com/photo-1576091160500-112173e7f9db?w=800&h=400&fit=crop',
    description: 'Coronary artery bypass grafting for heart disease treatment.',
    avgCost: { min: 15000, max: 35000 },
    duration: '5-7 days',
    successRate: 95,
    recovery: '4-6 weeks',
    hospitals: ['Apollo Hospital Delhi', 'Max Healthcare Bangalore'],
    doctors: ['Dr. Rajesh Sharma'],
  },
  {
    id: 2,
    slug: 'knee-replacement',
    name: 'Knee Replacement Surgery',
    category: 'Orthopedics',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=400&fit=crop',
    description: 'Total knee replacement for osteoarthritis and joint degeneration.',
    avgCost: { min: 12000, max: 25000 },
    duration: '2-3 days',
    successRate: 98,
    recovery: '3-6 months',
    hospitals: ['Max Healthcare Bangalore', 'Fortis Hospital Hyderabad'],
    doctors: ['Dr. Priya Gupta', 'Dr. Ali Raza'],
  },
  {
    id: 3,
    slug: 'cancer-treatment',
    name: 'Advanced Cancer Treatment',
    category: 'Oncology',
    image: 'https://images.unsplash.com/photo-1576091160949-112173e7f9db?w=800&h=400&fit=crop',
    description: 'Comprehensive cancer care including chemotherapy, radiation, and immunotherapy.',
    avgCost: { min: 20000, max: 60000 },
    duration: '3-6 months',
    successRate: 85,
    recovery: 'Varies',
    hospitals: ['Apollo Hospital Delhi', 'Fortis Hospital Hyderabad'],
    doctors: ['Dr. Aisha Khan'],
  },
  {
    id: 4,
    slug: 'brain-surgery',
    name: 'Brain Tumor Surgery',
    category: 'Neurosurgery',
    image: 'https://images.unsplash.com/photo-1576091160395-112173e7f9db?w=800&h=400&fit=crop',
    description: 'Minimally invasive brain tumor removal using advanced imaging.',
    avgCost: { min: 25000, max: 50000 },
    duration: '3-5 days',
    successRate: 92,
    recovery: '6-8 weeks',
    hospitals: ['Apollo Hospital Delhi', 'American Hospital Dubai'],
    doctors: ['Dr. Ahmed Hassan'],
  },
  {
    id: 5,
    slug: 'dental-implants',
    name: 'Dental Implants',
    category: 'Dentistry',
    image: 'https://images.unsplash.com/photo-1606811841689-23db3d821bda?w=800&h=400&fit=crop',
    description: 'Tooth replacement with advanced titanium implants.',
    avgCost: { min: 800, max: 2500 },
    duration: '1-2 days',
    successRate: 98,
    recovery: '3-6 months',
    hospitals: ['Apollo Hospital Delhi', 'Max Healthcare Bangalore'],
    doctors: [],
  },
];

export const countries = [
  {
    id: 1,
    slug: 'india',
    name: 'India',
    image: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&h=400&fit=crop',
    description: 'Premier medical tourism destination offering world-class healthcare at affordable prices.',
    hospitals: 3,
    avgCost: 'Starting from $5,000',
    visaDays: 60,
    specialities: ['Cardiology', 'Orthopedics', 'Oncology', 'Dentistry'],
    highlights: ['30-80% cost savings', 'Advanced technology', 'English-speaking doctors'],
  },
  {
    id: 2,
    slug: 'uae',
    name: 'United Arab Emirates',
    image: 'https://images.unsplash.com/photo-1512453315462-35149a37426f?w=800&h=400&fit=crop',
    description: 'Luxury medical facilities with premium healthcare services.',
    hospitals: 1,
    avgCost: 'Starting from $15,000',
    visaDays: 30,
    specialities: ['Cardiology', 'IVF', 'Dermatology', 'Orthopedics'],
    highlights: ['Premium facilities', 'Modern infrastructure', 'Tourism opportunities'],
  },
  {
    id: 3,
    slug: 'pakistan',
    name: 'Pakistan',
    image: 'https://images.unsplash.com/photo-1593272715884-b88fdfb4b38f?w=800&h=400&fit=crop',
    description: 'Growing medical hub with quality healthcare and cultural connectivity.',
    hospitals: 1,
    avgCost: 'Starting from $4,000',
    visaDays: 90,
    specialities: ['Orthopedics', 'Cardiac Surgery', 'General Surgery'],
    highlights: ['Cultural affinity', 'Affordable costs', 'Experienced surgeons'],
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Sarah Johnson',
    location: 'USA',
    treatment: 'Knee Replacement',
    hospital: 'Max Healthcare Bangalore',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    text: 'Amazing experience! The staff was incredibly professional and caring. I saved 80% on my surgery costs.',
    rating: 5,
  },
  {
    id: 2,
    name: 'James Wilson',
    location: 'Canada',
    treatment: 'Heart Bypass Surgery',
    hospital: 'Apollo Hospital Delhi',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    text: 'Exceptional care from top surgeons. The entire experience was seamless from consultation to recovery.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Maria Garcia',
    location: 'Spain',
    treatment: 'Dental Implants',
    hospital: 'Apollo Hospital Delhi',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    text: 'Best decision I made. Professional doctors, modern facilities, and unbeatable prices!',
    rating: 5,
  },
  {
    id: 4,
    name: 'Ahmed Mohamed',
    location: 'Saudi Arabia',
    treatment: 'Brain Surgery',
    hospital: 'American Hospital Dubai',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    text: 'Top-notch medical expertise combined with warm hospitality. Highly recommended!',
    rating: 5,
  },
  {
    id: 5,
    name: 'Lisa Chen',
    location: 'Australia',
    treatment: 'Orthopedic Surgery',
    hospital: 'Fortis Hospital Hyderabad',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    text: 'The care I received was world-class. I\'m back to normal life in just 4 months!',
    rating: 5,
  },
];

export const blogPosts = [
  {
    id: 1,
    slug: 'cost-savings-medical-tourism',
    title: 'How Medical Tourism Can Save You Up to 80% on Healthcare Costs',
    author: 'Dr. Priya Sharma',
    date: '2024-04-15',
    image: 'https://images.unsplash.com/photo-1576091160500-112173e7f9db?w=400&h=200&fit=crop',
    excerpt: 'Explore the financial benefits of choosing medical tourism for your healthcare needs.',
    category: 'Cost Savings',
  },
  {
    id: 2,
    slug: 'preparing-for-surgery',
    title: 'Complete Guide to Preparing for Your Medical Tourism Surgery',
    author: 'Dr. Rajesh Kumar',
    date: '2024-04-10',
    image: 'https://images.unsplash.com/photo-1631217314831-c6227db76b6e?w=400&h=200&fit=crop',
    excerpt: 'Essential tips and checklist for preparing yourself before your surgery abroad.',
    category: 'Patient Guide',
  },
  {
    id: 3,
    slug: 'recovery-tips',
    title: 'Post-Surgery Recovery: Tips for a Smooth Healing Process',
    author: 'Dr. Aisha Khan',
    date: '2024-04-05',
    image: 'https://images.unsplash.com/photo-1576091160395-112173e7f9db?w=400&h=200&fit=crop',
    excerpt: 'Follow these expert recommendations for optimal recovery after your surgery.',
    category: 'Recovery',
  },
];

export const faqs = [
  {
    id: 1,
    question: 'Is medical tourism safe?',
    answer: 'Yes, our partner hospitals are internationally accredited (JCI, NABH) and employ experienced surgeons trained globally.',
  },
  {
    id: 2,
    question: 'What about visa requirements?',
    answer: 'Most countries offer medical visas with extended validity. Our team assists with all visa-related documentation.',
  },
  {
    id: 3,
    question: 'Do you provide travel arrangements?',
    answer: 'Yes, we arrange flights, accommodation, and airport transfers as part of our comprehensive packages.',
  },
  {
    id: 4,
    question: 'What is the cost difference?',
    answer: 'On average, you can save 50-80% compared to Western countries while receiving care from world-class surgeons.',
  },
  {
    id: 5,
    question: 'How long is the recovery period?',
    answer: 'Recovery varies by procedure. Most patients return to normal activities within 2-12 weeks.',
  },
  {
    id: 6,
    question: 'Will there be follow-up care?',
    answer: 'Yes, we provide online follow-ups and coordinate with your local doctor for post-operative care.',
  },
];
