export const hospitals = [
  {
    id: 1,
    name: 'Apollo Hospitals',
    location: 'Delhi NCR',
    beds: 500,
    doctors: 200,
    rating: 4.8,
    description: 'One of India\'s leading healthcare providers with state-of-the-art facilities and experienced doctors.',
    badges: ['JCI Accredited', 'NABH Certified'],
    phoneNumber: '+919876543210',
    email: 'apollo@gdhealthcare.com',
  },
  {
    id: 2,
    name: 'Fortis Healthcare',
    location: 'Bangalore',
    beds: 450,
    doctors: 180,
    rating: 4.7,
    description: 'Advanced surgical and diagnostic facilities with expert specialist doctors across multiple disciplines.',
    badges: ['NABH Certified', 'ISO 9001:2015'],
    phoneNumber: '+919876543210',
    email: 'fortis@gdhealthcare.com',
  },
  {
    id: 3,
    name: 'Max Healthcare',
    location: 'Mumbai',
    beds: 400,
    doctors: 150,
    rating: 4.6,
    description: 'Comprehensive healthcare services with advanced treatment options and patient-centric approach.',
    badges: ['JCI Accredited', 'NABH Certified'],
    phoneNumber: '+919876543210',
    email: 'max@gdhealthcare.com',
  },
  {
    id: 4,
    name: 'Manipal Hospitals',
    location: 'Bangalore',
    beds: 350,
    doctors: 140,
    rating: 4.5,
    description: 'Integrated healthcare delivery system with cutting-edge technology and world-class infrastructure.',
    badges: ['NABH Certified'],
    phoneNumber: '+919876543210',
    email: 'manipal@gdhealthcare.com',
  },
  {
    id: 5,
    name: 'Indraprastha Apollo',
    location: 'Delhi NCR',
    beds: 520,
    doctors: 210,
    rating: 4.8,
    description: 'One of Delhi\'s premier hospitals offering comprehensive medical care across all specialties.',
    badges: ['JCI Accredited', 'NABH Certified', 'ISO Certified'],
    phoneNumber: '+919876543210',
    email: 'indraprastha@gdhealthcare.com',
  },
  {
    id: 6,
    name: 'Kokilaben Hospital',
    location: 'Mumbai',
    beds: 380,
    doctors: 160,
    rating: 4.7,
    description: 'State-of-the-art superspecialty hospital with advanced medical technology and expert doctors.',
    badges: ['JCI Accredited'],
    phoneNumber: '+919876543210',
    email: 'kokilaben@gdhealthcare.com',
  },
];

export const doctors = [
  {
    id: 1,
    name: 'Dr. Rajesh Kumar',
    specialty: 'Orthopedic Surgery',
    hospital: 'Apollo Hospitals',
    experience: 18,
    qualifications: ['MS Orthopedics', 'Fellowship in Joint Replacement'],
    phoneNumber: '+919876543210',
    email: 'rajesh@gdhealthcare.com',
  },
  {
    id: 2,
    name: 'Dr. Priya Sharma',
    specialty: 'Cardiology',
    hospital: 'Max Healthcare',
    experience: 16,
    qualifications: ['MD Cardiology', 'Fellowship in Interventional Cardiology'],
    phoneNumber: '+919876543210',
    email: 'priya@gdhealthcare.com',
  },
  {
    id: 3,
    name: 'Dr. Anil Gupta',
    specialty: 'Neurosurgery',
    hospital: 'Indraprastha Apollo',
    experience: 20,
    qualifications: ['MCh Neurosurgery', 'Fellowship in Spine Surgery'],
    phoneNumber: '+919876543210',
    email: 'anil@gdhealthcare.com',
  },
  {
    id: 4,
    name: 'Dr. Meera Nair',
    specialty: 'Oncology',
    hospital: 'Fortis Healthcare',
    experience: 17,
    qualifications: ['MD Oncology', 'Fellowship in Radiation Oncology'],
    phoneNumber: '+919876543210',
    email: 'meera@gdhealthcare.com',
  },
  {
    id: 5,
    name: 'Dr. Vikram Singh',
    specialty: 'Urology',
    hospital: 'Manipal Hospitals',
    experience: 15,
    qualifications: ['MS Urology', 'Fellowship in Uro-oncology'],
    phoneNumber: '+919876543210',
    email: 'vikram@gdhealthcare.com',
  },
  {
    id: 6,
    name: 'Dr. Neha Kapoor',
    specialty: 'Gynecology',
    hospital: 'Kokilaben Hospital',
    experience: 14,
    qualifications: ['MD Obstetrics & Gynecology', 'Fellowship in Gynecology Oncology'],
    phoneNumber: '+919876543210',
    email: 'neha@gdhealthcare.com',
  },
];

export const treatments = [
  {
    icon: '🦴',
    title: 'Orthopedic Surgery',
    description: 'Joint replacement, spine surgery, and trauma care with world-class expertise.',
  },
  {
    icon: '❤️',
    title: 'Cardiac Care',
    description: 'Comprehensive heart care from diagnosis to advanced surgical interventions.',
  },
  {
    icon: '🧠',
    title: 'Neurology & Neurosurgery',
    description: 'Brain and spinal cord treatments with advanced diagnostic facilities.',
  },
  {
    icon: '🩺',
    title: 'Oncology',
    description: 'Cancer treatment with latest chemotherapy and radiation therapy options.',
  },
  {
    icon: '👶',
    title: 'Fertility & IVF',
    description: 'Advanced reproductive medicine and fertility treatments with high success rates.',
  },
  {
    icon: '🦷',
    title: 'Dental Surgery',
    description: 'Complete dental care including implants and cosmetic procedures.',
  },
];

export const services = [
  {
    icon: '🛂',
    title: 'Visa Assistance',
    description: 'Complete support with visa applications and documentation for medical travel.',
    color: 'teal' as const,
  },
  {
    icon: '🏨',
    title: 'Accommodation',
    description: 'Comfortable accommodation arrangements near hospitals for patients and attendants.',
    color: 'blue' as const,
  },
  {
    icon: '🚗',
    title: 'Airport Transport',
    description: 'Pickup and drop services from airport to hospital and accommodation.',
    color: 'green' as const,
  },
  {
    icon: '🗣️',
    title: 'Interpreter Support',
    description: 'Professional interpreters for seamless communication with healthcare providers.',
    color: 'orange' as const,
  },
  {
    icon: '📋',
    title: 'Insurance Coordination',
    description: 'Expert assistance in insurance claims and documentation.',
    color: 'purple' as const,
  },
  {
    icon: '🩹',
    title: 'Follow-up Care',
    description: 'Continuous post-treatment follow-up and telemedicine consultations.',
    color: 'cyan' as const,
  },
  {
    icon: '💰',
    title: 'Financial Planning',
    description: 'Transparent pricing and flexible payment plans for affordable treatment.',
    color: 'teal' as const,
  },
  {
    icon: '✈️',
    title: 'Travel Coordination',
    description: 'Complete travel arrangements and itinerary planning for medical tourism.',
    color: 'blue' as const,
  },
];

export const testimonials = [
  {
    name: 'Maria Rodriguez',
    country: 'Spain',
    condition: 'Knee Replacement',
    testimonial: 'The treatment was exceptional, and the cost was less than half of what I would have paid in Spain. The doctors were highly skilled and very professional.',
    rating: 5,
  },
  {
    name: 'Ahmed Al-Rashid',
    country: 'UAE',
    condition: 'Heart Surgery',
    testimonial: 'GD Healthcare made the entire process seamless. From visa to post-operative care, everything was perfectly coordinated. Highly recommended!',
    rating: 5,
  },
  {
    name: 'Elena Popov',
    country: 'Russia',
    condition: 'Cancer Treatment',
    testimonial: 'The medical team was world-class and the care was compassionate. I felt safe and confident throughout my treatment journey.',
    rating: 5,
  },
  {
    name: 'John Smith',
    country: 'UK',
    condition: 'Hip Replacement',
    testimonial: 'Excellent results at a fraction of UK costs. The doctors were highly experienced and the facilities were state-of-the-art.',
    rating: 5,
  },
  {
    name: 'Sophie Laurent',
    country: 'France',
    condition: 'Fertility Treatment',
    testimonial: 'The fertility clinic was amazing. We got our dream of becoming parents thanks to their expertise and care.',
    rating: 5,
  },
  {
    name: 'Hassan Ibrahim',
    country: 'Egypt',
    condition: 'Spine Surgery',
    testimonial: 'Professional, affordable, and effective. I recommend GD Healthcare to all my friends and family.',
    rating: 5,
  },
];
